
name:  Docker Image CI_Demo
on: push
jobs:
  build-container:
    name: Build Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Publish to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.PERSONAL_TOKEN }}
          registry: github.com
          repository: ${{ github.repository }}/next
          tags: latest,${{ github.run_number }}
      - name: Publish to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: github.com
          repository: demo_docker/next
          tags: latest,${{ github.run_number }}
